title: "Kyle  P.  O'Brien" # your name (or website title) here
logo: "/images/headshot.jpg?raw=true" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a senior undergraduate student at the University of Maryland, Baltimore County (UMBC) studying <strong>Political Science</strong>, <strong>History</strong>, and <strong>GIS</strong>.  
  <br><br>
  I am reachable by e-mail at kobrien2@umbc.edu or kyleobrien1204@gmail.com and by phone at 443-900-4066.
  <br><br>
  Please feel free to contact me with any questions or comments. 
  <br>
theme: jekyll-theme-minimal
google_analytics: 302061016 # your Google Analytics tracking ID here
