title: "Kyle  P.  O'Brien" # your name (or website title) here
logo: "/images/city.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior undergraduate student at the University of Maryland Baltimore County (UMBC) studying Political Science, History, and GIS.
  <br><br>
  This page will display some of my projects in GIS and Cartography and serve as a professional development portfolio.
  <br><br>
  I am reachable by e-mail at either **kobrien2@umbc.edu** or **kyleobrien1204@gmail.com**

theme: jekyll-theme-minimal
google_analytics: 302061016 # your Google Analytics tracking ID here
