title: "Kyle O'Brien" # your name (or website title) here
logo: "IMG_7123.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior undergraduate student at UMBC studying Political Science, History, and GIS. This page will display some of my projects in GIS and supplement my professional portfolio.
  <br><br>
  <a href="www.linkedin.com/in/kyle-p-obrien">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 302061016 # your Google Analytics tracking ID here
