title: "Kyle O'Brien" # your name (or website title) here
logo: "/images/city.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I am a senior undergraduate student at the University of Maryland Baltimore County (UMBC) studying Political Science, History, and GIS. This page will display some of my projects in GIS and serve as a professional development portfolio.
  <br><br>
  <a href="http://www.linkedin.com/in/kyle-p-obrien">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 302061016 # your Google Analytics tracking ID here
